spring:
  application:
    name: alojamientos

  datasource:
    url: jdbc:mariadb://localhost:3306/alojamientos_db
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: update       # en prod usa 'none' + migraciones
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    problemdetails:
      enabled: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

# --- CORS (usado por CorsConfig) ---
cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"

# --- JWT (si usas JwtService) ---
app:
  jwt:
    secret: "d3v_5up3r_53cr3t_Cl4v3_L4rg4_y_4l34t0r14_Para_JWT_1234567890"
    expiration-minutes: 120
